PRACTICE_FIELD_GROUPS = {
    "Shooting": [
        {"key": "fg", "label": "FG", "format": "shooting_split"},
        {"key": "fg3", "label": "3FG", "format": "shooting_split"},
        {"key": "ft", "label": "FT", "format": "shooting_split"},
        {"key": "efg", "label": "eFG%", "format": "percent"},
        {"key": "shooting_atr_makes", "label": "ATR Makes", "format": "count"},
        {"key": "shooting_atr_attempts", "label": "ATR Attempts", "format": "count"},
        {"key": "shooting_atr_pct", "label": "ATR %", "format": "percent"},
        {"key": "shooting_atr_freq_pct", "label": "ATR Freq.", "format": "percent"},
        {"key": "shooting_fg2_makes", "label": "2FG Makes", "format": "count"},
        {"key": "shooting_fg2_attempts", "label": "2FG Attempts", "format": "count"},
        {"key": "shooting_fg2_pct", "label": "2FG %", "format": "percent"},
        {"key": "shooting_fg2_freq_pct", "label": "2FG Freq.", "format": "percent"},
        {"key": "shooting_fg3_attempts", "label": "3FG Attempts", "format": "count"},
        {"key": "shooting_fg3_pct", "label": "3FG %", "format": "percent"},
        {"key": "shooting_fg3_freq_pct", "label": "3FG Freq.", "format": "percent"},
        {"key": "shooting_ft_makes", "label": "FT Makes", "format": "count"},
        {"key": "shooting_ft_attempts", "label": "FT Attempts", "format": "count"},
        {"key": "shooting_ft_pct", "label": "FT %", "format": "percent"},
        {"key": "shooting_pps", "label": "PPS", "format": "ratio"},
        {"key": "shooting_efg_pct", "label": "eFG %", "format": "percent"},
    ],
    "Playmaking": [
        {"key": "play_ast", "label": "Assists", "format": "count"},
        {"key": "play_to", "label": "Turnovers", "format": "count"},
        {"key": "play_potential_ast", "label": "Pot. Assists", "format": "count"},
        {"key": "play_second_ast", "label": "2nd Assists", "format": "count"},
        {"key": "play_ast_to_ratio", "label": "Ast/TO Ratio", "format": "ratio"},
        {"key": "play_adj_ast_to_ratio", "label": "Adj Ast/TO Ratio", "format": "ratio"},
        {"key": "play_team_turnover_rate_on", "label": "All TO% — Team (On)", "format": "percent"},
        {"key": "play_indiv_turnover_rate", "label": "All TO% — Individual", "format": "percent"},
        {"key": "play_bamalytics_turnover_rate", "label": "All TO% — Bamalytics", "format": "percent"},
        {"key": "play_indiv_team_to_share", "label": "All TO% — Team Share", "format": "percent"},
    ],
    "Rebounding": [
        {"key": "reb", "label": "REB", "format": "count"},
        {"key": "oreb", "label": "OREB", "format": "count"},
        {"key": "dreb", "label": "DREB", "format": "count"},
        {"key": "rd_crash_plus", "label": "Crash +", "format": "count"},
        {"key": "rd_crash_att", "label": "Crash Att", "format": "count"},
        {"key": "rd_crash_pct", "label": "Crash %", "format": "percent"},
        {"key": "rd_back_plus", "label": "Back Man +", "format": "count"},
        {"key": "rd_back_att", "label": "Back Man Att", "format": "count"},
        {"key": "rd_back_pct", "label": "Back Man %", "format": "percent"},
        {"key": "rd_box_plus", "label": "Box Out +", "format": "count"},
        {"key": "rd_box_att", "label": "Box Out Att", "format": "count"},
        {"key": "rd_box_pct", "label": "Box Out %", "format": "percent"},
        {"key": "rd_given_up", "label": "Off Rebs Given Up", "format": "count"},
    ],
    "Traditional": [
        {"key": "pts", "label": "PTS", "format": "count"},
        {"key": "ast", "label": "AST", "format": "count"},
        {"key": "to", "label": "TO", "format": "count"},
        {"key": "stl", "label": "STL", "format": "count"},
        {"key": "blk", "label": "BLK", "format": "count"},
        {"key": "pf", "label": "PF", "format": "count"},
    ],
    "Advanced": [
        {"key": "ppp", "label": "PPP", "format": "ratio"},
        {"key": "atr", "label": "AST/TO", "format": "ratio"},
        {"key": "ft_rate", "label": "FT Rate", "format": "ratio"},
        {"key": "gs_pct", "label": "Good Shot %", "format": "percent"},
        {"key": "practice_oreb_pct", "label": "Practice OREB%", "format": "percent"},
        {"key": "pps", "label": "PPS", "format": "ratio"},
        {"key": "adv_ppp_on_offense", "label": "Offensive PPP (On)", "format": "ratio"},
        {"key": "adv_ppp_on_defense", "label": "Defensive PPP (On)", "format": "ratio"},
        {"key": "adv_ppp_off_offense", "label": "Offensive PPP (Off)", "format": "ratio"},
        {"key": "adv_ppp_off_defense", "label": "Defensive PPP (Off)", "format": "ratio"},
        {"key": "adv_offensive_possessions", "label": "Offensive Possessions", "format": "count"},
        {"key": "adv_defensive_possessions", "label": "Defensive Possessions", "format": "count"},
        {"key": "adv_off_reb_rate", "label": "Off Rebound Rate", "format": "percent"},
        {"key": "adv_def_reb_rate", "label": "Def Rebounding Rate", "format": "percent"},
    ],
    "On-Floor Rates": [
        {"key": "on_floor_oreb_pct", "label": "On-Floor OREB%", "format": "percent"},
        {"key": "on_floor_dreb_pct", "label": "On-Floor DREB%", "format": "percent"},
    ],
    "Blue Collar": [
        {"key": "bcp_total", "label": "BCP Total", "format": "count"},
        {"key": "deflections", "label": "Deflections", "format": "count"},
        {"key": "charges", "label": "Charges Taken", "format": "count"},
        {"key": "floor_dives", "label": "Floor Dives", "format": "count"},
        {"key": "loose_balls_won", "label": "Loose Balls Won", "format": "count"},
        {"key": "tips", "label": "Tips", "format": "count"},
        {"key": "steals_bc", "label": "Steals (BC)", "format": "count"},
        {"key": "blocks_bc", "label": "Blocks (BC)", "format": "count"},
        {"key": "bc_total", "label": "BCP Total", "format": "count"},
        {"key": "bc_deflection", "label": "Deflection", "format": "count"},
        {"key": "bc_charges_taken", "label": "Charges Taken", "format": "count"},
        {"key": "bc_floor_dives", "label": "Floor Dives", "format": "count"},
        {"key": "bc_steals", "label": "Steals", "format": "count"},
        {"key": "bc_tips", "label": "Tips", "format": "count"},
    ],
}
