PRACTICE_FIELD_GROUPS = {
    "Shooting": [
        {"key": "fg", "label": "FG", "format": "shooting_split"},
        {"key": "fg3", "label": "3FG", "format": "shooting_split"},
        {"key": "ft", "label": "FT", "format": "shooting_split"},
        {"key": "efg", "label": "eFG%", "format": "percent"},
    ],
    "Rebounding": [
        {"key": "reb", "label": "REB", "format": "count"},
        {"key": "oreb", "label": "OREB", "format": "count"},
        {"key": "dreb", "label": "DREB", "format": "count"},
        {"key": "rd_crash_plus", "label": "Crash +", "format": "count"},
        {"key": "rd_crash_att", "label": "Crash Att", "format": "count"},
        {"key": "rd_crash_pct", "label": "Crash %", "format": "percent"},
        {"key": "rd_back_plus", "label": "Back Man +", "format": "count"},
        {"key": "rd_back_att", "label": "Back Man Att", "format": "count"},
        {"key": "rd_back_pct", "label": "Back Man %", "format": "percent"},
        {"key": "rd_box_plus", "label": "Box Out +", "format": "count"},
        {"key": "rd_box_att", "label": "Box Out Att", "format": "count"},
        {"key": "rd_box_pct", "label": "Box Out %", "format": "percent"},
        {"key": "rd_given_up", "label": "Off Rebs Given Up", "format": "count"},
    ],
    "Traditional": [
        {"key": "pts", "label": "PTS", "format": "count"},
        {"key": "ast", "label": "AST", "format": "count"},
        {"key": "to", "label": "TO", "format": "count"},
        {"key": "stl", "label": "STL", "format": "count"},
        {"key": "blk", "label": "BLK", "format": "count"},
        {"key": "pf", "label": "PF", "format": "count"},
    ],
    "Advanced": [
        {"key": "ppp", "label": "PPP", "format": "ratio"},
        {"key": "atr", "label": "AST/TO", "format": "ratio"},
        {"key": "ft_rate", "label": "FT Rate", "format": "ratio"},
        {"key": "gs_pct", "label": "Good Shot %", "format": "percent"},
        {"key": "oreb_pct", "label": "OREB%", "format": "percent"},
        {"key": "pps", "label": "PPS", "format": "ratio"},
    ],
    "Blue Collar": [
        {"key": "bcp_total", "label": "BCP Total", "format": "count"},
        {"key": "deflections", "label": "Deflections", "format": "count"},
        {"key": "charges", "label": "Charges Taken", "format": "count"},
        {"key": "floor_dives", "label": "Floor Dives", "format": "count"},
        {"key": "loose_balls_won", "label": "Loose Balls Won", "format": "count"},
        {"key": "tips", "label": "Tips", "format": "count"},
        {"key": "steals_bc", "label": "Steals (BC)", "format": "count"},
        {"key": "blocks_bc", "label": "Blocks (BC)", "format": "count"},
    ],
}
