"""Add practice_wins, practice_losses, sprint_wins, sprint_losses to PlayerStats

Revision ID: 108e107ba16c
Revises: c2a1402528b8
Create Date: 2025-06-05 16:44:50.570182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108e107ba16c'
down_revision = 'c2a1402528b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprint_wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sprint_losses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_column('sprint_losses')
        batch_op.drop_column('sprint_wins')

    # ### end Alembic commands ###
