"""create page_view table

Revision ID: 18ec91f6d3af
Revises: fa05b941a8bd
Create Date: 2025-06-25 22:01:01.409925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ec91f6d3af'
down_revision = 'fa05b941a8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'page_view',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('endpoint', sa.String(length=128), nullable=False),
        sa.Column('path', sa.String(length=256), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('user_agent', sa.String(length=256), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade():
    op.drop_table('page_view')
