"""Add parse_error and breakdown fields to uploaded_files

Revision ID: 26f3a43581af
Revises: bfac7702b9be
Create Date: 2025-04-23 19:53:55.493456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f3a43581af'
down_revision = 'bfac7702b9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parse_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('offensive_breakdown', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('defensive_breakdown', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('lineup_efficiencies', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('lineup_efficiencies')
        batch_op.drop_column('defensive_breakdown')
        batch_op.drop_column('offensive_breakdown')
        batch_op.drop_column('parse_error')

    # ### end Alembic commands ###
