"""Add is_player and player_name to User

Revision ID: 391bce30cc77
Revises: 108e107ba16c
Create Date: 2025-06-05 18:54:45.098352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391bce30cc77'
down_revision = '108e107ba16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_player', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('player_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('player_name')
        batch_op.drop_column('is_player')

    # ### end Alembic commands ###
