"""Add season_id to uploaded_files

Revision ID: 69327cb88861
Revises: 108e107ba16c
Create Date: 2025-06-05 22:02:33.806552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69327cb88861'
down_revision = '108e107ba16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprint_wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sprint_losses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_column('sprint_losses')
        batch_op.drop_column('sprint_wins')

    # ### end Alembic commands ###
