"""Add practice_wins and practice_losses to PlayerStats

Revision ID: 768821f51dd5
Revises: ca4ae573fef1
Create Date: 2025-06-02 14:49:11.330663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768821f51dd5'
down_revision = 'ca4ae573fef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice_wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('practice_losses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_column('practice_losses')
        batch_op.drop_column('practice_wins')

    # ### end Alembic commands ###
