"""Create PnRStats table

Revision ID: 929486bc4df5
Revises: dfc35024adde
Create Date: 2025-06-17 18:34:32.505140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929486bc4df5'
down_revision = 'dfc35024adde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_stats', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_stats', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
