"""Add missing recruit columns

Revision ID: a99d84b087da
Revises: ddbf220420b8
Create Date: 2025-07-28 09:45:00.923558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99d84b087da'
down_revision = 'ddbf220420b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('high_school', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('hometown', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ranking', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('camp_performance', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('offer_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('offer_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('commit_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headshot_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_uploaded_files_recruit_id',  # Explicit constraint name
            'recruit',
            ['recruit_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_uploaded_files_recruit_id', type_='foreignkey')

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.drop_column('headshot_filename')

    with op.batch_alter_table('recruit', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('commit_date')
        batch_op.drop_column('offer_date')
        batch_op.drop_column('offer_status')
        batch_op.drop_column('camp_performance')
        batch_op.drop_column('ranking')
        batch_op.drop_column('rating')
        batch_op.drop_column('hometown')
        batch_op.drop_column('high_school')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
    # ### end Alembic commands ###
