"""Initial migration

Revision ID: bfac7702b9be
Revises: 
Create Date: 2025-03-19 19:56:19.408600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfac7702b9be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_name')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('parse_status', sa.String(length=50), nullable=True),
    sa.Column('parse_log', sa.Text(), nullable=True),
    sa.Column('last_parsed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent_name', sa.String(length=100), nullable=False),
    sa.Column('home_or_away', sa.String(length=10), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('csv_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('atr_makes', sa.Integer(), nullable=True),
    sa.Column('atr_attempts', sa.Integer(), nullable=True),
    sa.Column('fg2_makes', sa.Integer(), nullable=True),
    sa.Column('fg2_attempts', sa.Integer(), nullable=True),
    sa.Column('fg3_makes', sa.Integer(), nullable=True),
    sa.Column('fg3_attempts', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('second_assists', sa.Integer(), nullable=True),
    sa.Column('pot_assists', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('foul_by', sa.Integer(), nullable=True),
    sa.Column('contest_front', sa.Integer(), nullable=True),
    sa.Column('contest_side', sa.Integer(), nullable=True),
    sa.Column('contest_behind', sa.Integer(), nullable=True),
    sa.Column('contest_late', sa.Integer(), nullable=True),
    sa.Column('contest_no', sa.Integer(), nullable=True),
    sa.Column('contest_early', sa.Integer(), nullable=True),
    sa.Column('bump_positive', sa.Integer(), nullable=True),
    sa.Column('bump_missed', sa.Integer(), nullable=True),
    sa.Column('blowby_total', sa.Integer(), nullable=True),
    sa.Column('blowby_triple_threat', sa.Integer(), nullable=True),
    sa.Column('blowby_closeout', sa.Integer(), nullable=True),
    sa.Column('blowby_isolation', sa.Integer(), nullable=True),
    sa.Column('atr_fouled', sa.Integer(), nullable=True),
    sa.Column('fg2_fouled', sa.Integer(), nullable=True),
    sa.Column('fg3_fouled', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_stats_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_stats_player_name'), ['player_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_stats_season_id'), ['season_id'], unique=False)

    op.create_table('possession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('time_segment', sa.String(length=20), nullable=True),
    sa.Column('possession_side', sa.Boolean(), nullable=True),
    sa.Column('player_combinations', sa.String(length=255), nullable=True),
    sa.Column('possession_start', sa.String(length=50), nullable=True),
    sa.Column('possession_type', sa.String(length=50), nullable=True),
    sa.Column('paint_touches', sa.String(length=10), nullable=True),
    sa.Column('shot_clock', sa.String(length=10), nullable=True),
    sa.Column('shot_clock_pt', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('possession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_possession_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_possession_season_id'), ['season_id'], unique=False)

    op.create_table('team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('total_assists', sa.Integer(), nullable=True),
    sa.Column('total_turnovers', sa.Integer(), nullable=True),
    sa.Column('total_second_assists', sa.Integer(), nullable=True),
    sa.Column('total_pot_assists', sa.Integer(), nullable=True),
    sa.Column('total_atr_makes', sa.Integer(), nullable=True),
    sa.Column('total_atr_attempts', sa.Integer(), nullable=True),
    sa.Column('total_fg2_makes', sa.Integer(), nullable=True),
    sa.Column('total_fg2_attempts', sa.Integer(), nullable=True),
    sa.Column('total_fg3_makes', sa.Integer(), nullable=True),
    sa.Column('total_fg3_attempts', sa.Integer(), nullable=True),
    sa.Column('total_fta', sa.Integer(), nullable=True),
    sa.Column('total_ftm', sa.Integer(), nullable=True),
    sa.Column('total_blue_collar', sa.Integer(), nullable=True),
    sa.Column('total_possessions', sa.Integer(), nullable=True),
    sa.Column('is_opponent', sa.Boolean(), nullable=True),
    sa.Column('total_atr_fouled', sa.Integer(), nullable=True),
    sa.Column('total_fg2_fouled', sa.Integer(), nullable=True),
    sa.Column('total_fg3_fouled', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_stats_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_stats_season_id'), ['season_id'], unique=False)

    op.create_table('blue_collar_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('def_reb', sa.Integer(), nullable=True),
    sa.Column('off_reb', sa.Integer(), nullable=True),
    sa.Column('misc', sa.Integer(), nullable=True),
    sa.Column('deflection', sa.Integer(), nullable=True),
    sa.Column('steal', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('floor_dive', sa.Integer(), nullable=True),
    sa.Column('charge_taken', sa.Integer(), nullable=True),
    sa.Column('reb_tip', sa.Integer(), nullable=True),
    sa.Column('total_blue_collar', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player_stats.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blue_collar_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blue_collar_stats_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blue_collar_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blue_collar_stats_season_id'), ['season_id'], unique=False)

    op.create_table('opponent_blue_collar_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('def_reb', sa.Integer(), nullable=True),
    sa.Column('off_reb', sa.Integer(), nullable=True),
    sa.Column('misc', sa.Integer(), nullable=True),
    sa.Column('deflection', sa.Integer(), nullable=True),
    sa.Column('steal', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('floor_dive', sa.Integer(), nullable=True),
    sa.Column('charge_taken', sa.Integer(), nullable=True),
    sa.Column('reb_tip', sa.Integer(), nullable=True),
    sa.Column('total_blue_collar', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player_stats.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opponent_blue_collar_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opponent_blue_collar_stats_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opponent_blue_collar_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opponent_blue_collar_stats_season_id'), ['season_id'], unique=False)

    op.create_table('player_possession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('possession_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_stats.id'], ),
    sa.ForeignKeyConstraint(['possession_id'], ['possession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_possession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_possession_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_possession_possession_id'), ['possession_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_possession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_possession_possession_id'))
        batch_op.drop_index(batch_op.f('ix_player_possession_player_id'))

    op.drop_table('player_possession')
    with op.batch_alter_table('opponent_blue_collar_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opponent_blue_collar_stats_season_id'))
        batch_op.drop_index(batch_op.f('ix_opponent_blue_collar_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_opponent_blue_collar_stats_game_id'))

    op.drop_table('opponent_blue_collar_stats')
    with op.batch_alter_table('blue_collar_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blue_collar_stats_season_id'))
        batch_op.drop_index(batch_op.f('ix_blue_collar_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_blue_collar_stats_game_id'))

    op.drop_table('blue_collar_stats')
    with op.batch_alter_table('team_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_stats_season_id'))
        batch_op.drop_index(batch_op.f('ix_team_stats_game_id'))

    op.drop_table('team_stats')
    with op.batch_alter_table('possession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_possession_season_id'))
        batch_op.drop_index(batch_op.f('ix_possession_game_id'))

    op.drop_table('possession')
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_stats_season_id'))
        batch_op.drop_index(batch_op.f('ix_player_stats_player_name'))
        batch_op.drop_index(batch_op.f('ix_player_stats_game_id'))

    op.drop_table('player_stats')
    op.drop_table('game')
    op.drop_table('users')
    op.drop_table('uploaded_files')
    op.drop_table('season')
    # ### end Alembic commands ###
